services:
  web:
    build: .
    container_name: flask
    expose:
      - "5000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
  nginx:
    image: nginx:stable
    container_name: flask-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/app
      - ./nginx/certs:/etc/nginx/certs:ro
    restart: always
